version: "3.1"
services:
  db:
    container_name: lah_db
    image: postgres
    volumes:
      - ./lah_db:/var/lib/postgresql/data/
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    env_file:
      - ./backend/api/.env.docker
  api:
    container_name: api
    build: ./backend/api
    restart: always
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    expose: 
      - "${BACKEND_PORT}"
    depends_on:
      - db